title: SDVX en français !
description: Une base de connaissance en français autour de Sound Voltex.
theme: just-the-docs
color_scheme: dark

url: https://kb.sdvx.fr

aux_links:
  Discord Communautaire: https://asso-msn.fr/discord
